id: A00E06C7E
title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
type: translation
pechas:
- I921ECD5C
- I204D1332
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:03.447215
  last_modified_at: 2023-01-04 13:10:03.447220
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I921ECD5C/184C: 0AA9
  I204D1332/C5AE: 0AA9
